# uwsgi.ini file
[uwsgi]

# Django-related settings
# the base directory (full path)
chdir           = /app
# Django's wsgi file
module          = web_project.wsgi

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 10

# the socket (use the full path to be safe
#socket          = :8888

# ... with appropriate permissions - may be needed
# chmod-socket    = 664
# clear environment on exit
#vacuum          = true

static-map = /static=/app/static

http = :8000

# DO NOT USE IN PRODUCTION
py-autoreload   = 2
