# Generated by Django 3.2.7 on 2021-10-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive', models.IntegerField()),
                ('sample_time', models.DateTimeField()),
                ('temp_low', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('temp_high', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('temp_hot', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('temp_out', models.SmallIntegerField(blank=True, null=True)),
                ('temp_target', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('humi_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humi_out', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heat_pwr', models.SmallIntegerField(blank=True, null=True)),
                ('fan', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('heater_breakers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'samples_h',
                'managed': True,
                'unique_together': {('hive', 'sample_time')},
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive', models.IntegerField()),
                ('sample_time', models.DateTimeField()),
                ('temp_low', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('temp_high', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('temp_hot', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('temp_out', models.SmallIntegerField(blank=True, null=True)),
                ('temp_target', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('humi_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humi_out', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heat_pwr', models.SmallIntegerField(blank=True, null=True)),
                ('fan', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('heater_breakers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'samples',
                'managed': True,
                'unique_together': {('hive', 'sample_time')},
            },
        ),
    ]
