# Generated by Django 3.2.7 on 2022-01-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivebox', '0003_hivegroups_hives'),
    ]

    operations = [
        migrations.AddField(
            model_name='hives',
            name='hive_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
