# Generated by Django 3.2.7 on 2021-09-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={'managed': False},
        ),
    ]
